const APP_STRINGS = {
  areYouWilling: "Are You Willing to Travel Out of State for a Drone Job?",
  briefSummary: "Please Give Us a Brief Summary of Your Work Experience",
  choose: "Choose",
  doYouHaveValidInsurance: "Do you have valid insurance?",
  experienceFlying: "Have you had experience flying over 400 Feet?",
  haveYouHadExperienceFlying: "Have you had experience flying over 400 Feet?",
  hello: "Hello!",
  insurance: "Do You Have Valid Insurance?",
  modelDrone: "What Drone Model Do You Have?",
  noYearsOfExperience: "No Years of Experience",
  no: "No",
  none: "None",
  openModal: "Open modal",
  pleaseSetLocation: "Please Set Location",
  saveAndContinue: "Save and Continue",
  setWorkExperience: "Please Set Work Experience",
  successfullyUploaded: "Successfully Uploaded to the Hovrtek Database!",
  uploadImage: "Upload Image",
  slide: "slide",
  workExperienceSet: "Work Experience Set",
  whereIsTheLocation: "Were is the location of your drone service?",
  yearsExperience: "How Many Years Of Drone Experience Do You Have?",
  yes: "Yes",
};

export { APP_STRINGS };
